---
- include_vars: ../../vars_main.yml

- name: Instalar Apache
  apt:
    name: apache2
    update_cache: true
    cache_valid_time: 3600

- name: Apache virtualhost
  template:
    src: "files/{{ http_conf }}.j2"
    dest: "/etc/apache2/sites-available/{{ http_conf }}"

- name: Activar sitio
  shell: /usr/sbin/a2ensite {{ http_conf }}

- name: Habilitando modulos PHP
  shell: a2enmod rewrite headers dir mime env setenvif ssl
  notify: servicios_apache

