---
- include_vars: ../../vars_main.yml

- name: "Instalar PHP {{ php }} + dependencias"
  apt:
    name: "{{ item }}"
    update_cache: true
    cache_valid_time: 3600
  with_items: "{{ nextcloud_packages }}"

- name: Configurando php
  lineinfile:
    dest: "/etc/php/{{ php }}/apache2/php.ini"
    regexp: "{{ item.origen }}"
    line: "{{ item.destino }}"
  loop:
    - { origen: '^memory_limit', destino: 'memory_limit = 512M' }
    - { origen: '^;date.timezone', destino: 'date.timezone = America/Argentina/Buenos_Aires' }
    - { origen: '^upload_max_filesize', destino: 'upload_max_filesize = 2048M' }
    - { origen: '^post_max_size', destino: 'post_max_size = 2048M' }
    - { origen: '^max_execution_time', destino: 'max_execution_time = 600' }
    - { origen: '^output_buffering', destino: 'output_buffering = Off' }


- name: "Descarga y descomprime nextcloud {{ next_version }}"
  unarchive:
    src: "https://download.nextcloud.com/server/releases/{{ next_version }}.zip"
    dest: /var/www/html/
    owner: "{{ usuario_apache }}"
    group: "{{ grupo_apache }}"
    mode: 0755
    remote_src: true

- name: Creando directorio para datos
  file:
    path: /mnt/next-data
    state: directory
    owner: "{{ usuario_apache }}"
    group: "{{ grupo_apache }}"
    mode: 0755